### ISSUE TITLE
multiple rtsp flask implementation

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_DeepSort_OSNet#322]
Hello, 

    I'm working on app with multiple rtsp stream where I am using flask as a backend. There are multiple buttons on home page with the names of camera numbers. On click button camera1 it should open page with 1 st rtsp stream on streams.txt, on click camera2  -  the 2 nd and so on.  I know that in streams.txt index of the rtsp is 0 1 2 3... I could render only 1 rtsp stream on web page. But I don't know how to do it with multiple streams. Please, help me to solve this

**Comment by mikel-brostrom** [comment]
For multiple simultaneous streams you should check:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/tree/multi-video-tracking

**Comment by mikel-brostrom** [comment]
This branch got merged into master. Multi-video tracking is now optional by default
