### ISSUE TITLE
Invalid argument --save-txt for youtube video

### ISSUE THREAD

**Issue by Advist** [mikel-brostrom/Yolov5_DeepSort_OSNet#349]
Traceback (most recent call last):
  File "track.py", line 262, in <module>
    detect(opt)
  File "track.py", line 189, in detect
    with open(txt_path, 'a') as f:
OSError: [Errno 22] Invalid argument: 'runs\\track\\exp47/watch?v=WInT7NRq2Ss.txt'

**Comment by mikel-brostrom** [comment]
I see a windows path there. I have never tested this piece of software on windows and don't own a windows machine so I cannot do any debugging. Maybe somebody else could help here.
