### ISSUE TITLE
The result of MOTA is negative

### ISSUE THREAD

**Issue by hzq1112** [mikel-brostrom/Yolov5_DeepSort_OSNet#363]
No matter which weight file is used, the value of MOTA is negative. Is there a specific operation process, or which combination of two weight files is used?look forward to your answer

**Comment by mikel-brostrom** [comment]
MOTA is negative for which dataset? MOT16?

**Comment by hzq1112** [comment]
> MOTA is negative for which dataset? MOT16? In that case you should only be detect people. This can be done with the existing COCO models as shown in the eval script

I used the txt file I tracked to replace the official txt file, but almost all the numbers I got were negative, and when I tested the official tracking file, the result was normal again. The data set was MOTA16, and the weight file was yolov5x. I put Your own txt file is placed in the directory "MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16-train/crowdhuman_yolov5m_osnet_x0_75_imagenet/data"， and finally run run_mot_challenge to eval.  look forward to your answer

![image](https://user-images.githubusercontent.com/62466083/163507821-eb858029-077d-4ef5-86b2-cb315e375002.png)

results:
![image](https://user-images.githubusercontent.com/62466083/163507249-3cc9417e-354b-4072-98ac-93fe59bd12d5.png)

**Comment by mikel-brostrom** [comment]
Hmmm, I have seen that multiple people got the same evaluation results independently of which DeepSort model was used: https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/366. THis got fixed by the way. But I have never seen negative results...

**Comment by mikel-brostrom** [comment]
Feel free to share your evaluation results @hzq1112!
