### ISSUE TITLE
About the improved model

### ISSUE THREAD

**Issue by Him-wen** [mikel-brostrom/Yolov5_DeepSort_OSNet#364]
The author, may I ask if the improved model of yolov5 is used, such as using the improved yaml structure, improving the loss function, and adding the attention mechanism, can this warehouse still support the improved yolo v5 model?

**Comment by mikel-brostrom** [comment]
If you have made modification to Yolov5 you can replace the one used here by your own. You should be able to call it in the exact same way as in `track.py` as long as the output structure is the same
