### ISSUE TITLE
Same evaluation results independently of which DeepSort model is chosen

### ISSUE THREAD

**Issue by gridmankolt** [mikel-brostrom/Yolov5_DeepSort_OSNet#366]
Tried to start evaluation, passed through a bunch of errors related to the incorrectly written data output path in the script and ended up with this
```
Evaluating ch_yolov5m_deep_sort

    MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.2764 sec
Tracker ch_yolov5m_deep_sort was unable to be evaluated.
Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
Traceback (most recent call last):
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
Traceback (most recent call last):
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 180, in evaluate
    raise err
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
    data = dataset.get_preprocessed_seq_data(raw_data, cls)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
    result = f(*args, **kw)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
    self._check_unique_ids(raw_data)
  File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
    raise TrackEvalException(exc_str)
trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)

```
It happens after the last part in `eval.sh`: `run_mot_challenge.py` when it is trying to read `.txt` files

**Comment by gridmankolt** [comment]
Solved, just needed to reload the repo. But every evaluation process i have the same results for metrics, even though i change reid model with the `--deep_sort_model` parameter, is this correct?

**Comment by mikel-brostrom** [comment]
Are you sure that the `txt` files get overwritten? This was the reason behind, one of the latest updates, saving different result to their corresponding experiment folder: `runs/track/<yolo_model>_<deep_sort_model>/`. Have you pulled the latest updates?

**Comment by mikel-brostrom** [comment]
You should see different results

**Comment by gridmankolt** [comment]
> You should see different results

Im getting same results and `txts` for every run. This is what i changed in the `eval.sh` script:

- lines 83-84: I added only `--deep_sort_model mobilenetv2_x1_4_dukemtmcreid` (e.g. model name)
- lines 103-104: I changed the first path (and change it according to model name)
```
mv ~/Yolov5_DeepSort_Pytorch/runs/track/yolov5/weights/crowdhuman_yolov5m_mobilenetv2_x1_4_dukemtmcreid/tracks/* \
   ~/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/data/trackers/mot_challenge/MOT16-train/ch_yolov5m_deep_sort/data/
```
isnt it enough?

**Comment by gridmankolt** [comment]
pulled the latest updates, made first try with different models - same results in metrics:
[pedestrian_summary.txt](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/files/8499821/pedestrian_summary.txt)
I thought mb it is not using different model except osnet, but during evaluation im getting this message
`Successfully loaded pretrained weights from "deep_sort/deep/checkpoint/resnet50_MSMT17.pth"`
so, any other reasons why can it be?

**Comment by gridmankolt** [comment]
I've ran this manually with `--save-txt` command and got the same results on MOT16-02 img sequence with different reid models
[MOT16-02-resnet50.txt](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/files/8506756/MOT16-02-resnet50.txt)
[MOT16-02-osnet-ibn.txt](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/files/8506759/MOT16-02-osnet-ibn.txt)
fresh repo, crowdhuman weights and so on, why is it happening?

**Comment by HongShen-Z** [comment]
> Solved, just needed to reload the repo. But every evaluation process i have the same results for metrics, even though i change reid model with the `--deep_sort_model` parameter, is this correct?

Hi, I've met the same problem, do you solve it?

**Comment by HongShen-Z** [comment]
I may have found the problem. The metric used in deep_sort.py is euclidean_distance, and the max_dist in deep_sort.yaml is 0.2, which is consistently smaller than computed euclidean_distance. So the following app_gate is always true.
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/e263d94ddf9b4d5f30426a1eac508b335f5abb77/deep_sort/sort/tracker.py#L123
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/e263d94ddf9b4d5f30426a1eac508b335f5abb77/deep_sort/sort/tracker.py#L126
The cost_matrix values at app_gate are all set to INFTY_COST, which result in the same evaluation results.
The MOTA result is relatively high somehow in this way, I don't know why.

**Comment by gridmankolt** [comment]
> Hi, I've met the same problem, do you solve it?

The problem with same results? Nah - still waiting for author to answer...

**Comment by mikel-brostrom** [comment]
I introduced a bug in one of my latest updates according to: https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/374

Try again and let me know!

**Comment by mikel-brostrom** [comment]
Feel free to drop your evaluation results here @gridmankolt, @HongShen-Z!

**Comment by mikel-brostrom** [comment]
These are the results:

```bash
CLEAR: ch_yolov5m_deep_sort_msmt17-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag      
MOT16-02                           44.883    78.629    45.562    48.388    94.482    16.667    51.852    31.481    34.542    8629      9204      504       121       9         28        17        265       
MOT16-04                           69.903    78.607    70.061    76.849    91.884    46.988    37.349    15.663    53.464    36547     11010     3228      75        39        31        13        336       
MOT16-05                           43.972    78.653    44.896    51.203    89.033    21.6      56        22.4      33.041    3491      3327      430       63        27        70        28        153       
MOT16-09                           61.727    84.296    62.45     76.393    84.565    52        48        0         49.731    4016      1241      733       38        13        12        0         62        
MOT16-10                           63.038    76.889    63.639    69.93     91.746    35.185    53.704    11.111    46.876    8614      3704      775       74        19        29        6         333       
MOT16-11                           63.549    84.863    63.898    81.633    82.152    55.072    36.232    8.6957    51.192    7489      1685      1627      32        38        25        6         77        
MOT16-13                           51.721    76.841    52.253    57.878    91.143    28.972    42.056    28.972    38.317    6627      4823      644       61        31        45        31        189       
COMBINED                           60.692    79.185    61.112    68.305    90.473    34.043    46.422    19.536    46.474    75413     34994     7941      464       176       240       101       1415      

Identity: ch_yolov5m_deep_sort_msmt17-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP      
MOT16-02                           44.53     33.668    65.74     6004      11829     3129      
MOT16-04                           72.242    66.331    79.309    31545     16012     8230      
MOT16-05                           50.396    39.689    69.013    2706      4112      1215      
MOT16-09                           60.504    57.58     63.74     3027      2230      1722      
MOT16-10                           61.04     53.783    70.561    6625      5693      2764      
MOT16-11                           65.238    65.032    65.445    5966      3208      3150      
MOT16-13                           61.012    49.878    78.545    5711      5739      1560      
COMBINED                           63.567    55.779    73.882    61584     48823     21770     

Count: ch_yolov5m_deep_sort_msmt17-pedestrianDets      GT_Dets   IDs       GT_IDs    
MOT16-02                           9133      17833     148       54        
MOT16-04                           39775     47557     141       83        
MOT16-05                           3921      6818      114       125  
```

 I now get with: imgz 1280, crowdhuman_yolov5m, OSNet_x0_25_msmt17, alpha=0
Next step will be to train a larger Yolov5 model on CrowdHuman

**Comment by RiordaLJJ** [comment]
> Tried to start evaluation, passed through a bunch of errors related to the incorrectly written data output path in the script and ended up with this
> 
> ```
> Evaluating ch_yolov5m_deep_sort
> 
>     MotChallenge2DBox.get_raw_seq_data(ch_yolov5m_deep_sort, MOT16-02)     0.2764 sec
> Tracker ch_yolov5m_deep_sort was unable to be evaluated.
> Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
> Traceback (most recent call last):
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
> Traceback (most recent call last):
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/scripts/run_mot_challenge.py", line 91, in <module>
>     evaluator.evaluate(dataset_list, metrics_list)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 180, in evaluate
>     raise err
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 86, in evaluate
>     res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/eval.py", line 195, in eval_sequence
>     data = dataset.get_preprocessed_seq_data(raw_data, cls)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/_timing.py", line 17, in wrap
>     result = f(*args, **kw)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/mot_challenge_2d_box.py", line 323, in get_preprocessed_seq_data
>     self._check_unique_ids(raw_data)
>   File "/home/grid/Yolov5_DeepSort_Pytorch/MOT16_eval/TrackEval/trackeval/datasets/_base_dataset.py", line 315, in _check_unique_ids
>     raise TrackEvalException(exc_str)
> trackeval.utils.TrackEvalException: Tracker predicts the same ID more than once in a single timestep (seq: MOT16-02, frame: 3, ids: 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
> ```
> 
> It happens after the last part in `eval.sh`: `run_mot_challenge.py` when it is trying to read `.txt` files

Hi,I also met this problem and I saw your comment below,but I don't understand how to 'reload the repo' ,I 'm a freshman ,could you please tell me more about this?
