### ISSUE TITLE
Track features are not stored correctly in the cost matrix

### ISSUE THREAD

**Issue by denissabramovs** [mikel-brostrom/Yolov5_DeepSort_OSNet#371]
Want to share my thoughts about that issue here. I would open a discussion of that somewhere, to chat together with contributors.
I'm trying to understand the problem that forces tracking objects to switch to a new tracking object with a new tracking id.
I have found problematic place in the whole algorithm and i think it should be changed in some ways.

**Scene and actions description**:
It is a webcam stream, only my face is visible on the screen.
I'm covering my face with a towel for a few seconds and then remove it from the screen.

**Some of deepsort parameters are changed for problem catching**:
```
MAX_AGE: 300
N_INIT: 50
```

**Debugging logs**:
```
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.016s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.016s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.016s)
[Track 1|Matched!]
Track:1 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.016s)
[Track 1|State:2] missed, number of misses:1
No detections
[Track 1|State:2] missed, number of misses:2
No detections
[Track 1|State:2] missed, number of misses:3
No detections
[Track 1|State:2] missed, number of misses:4
No detections
[Track 1|State:2] missed, number of misses:5
No detections
[Track 1|State:2] missed, number of misses:6
No detections
[Track 1|State:2] missed, number of misses:7
No detections
[Track 1|State:2] missed, number of misses:8
No detections
[Track 1|State:2] missed, number of misses:9
No detections
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:10
Unmatched detection found!
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:11
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:12
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:13
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:14
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:15
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.009s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:16
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:17
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
[Track 2|Matched!]
[Track 1|Not Matched!]
[Track 1|State:2] missed, number of misses:18
Track:1 is Deleted: False
Track:2 is Deleted: False
0: 480x640 1 person, Done. YOLO:(0.008s), DeepSort:(0.015s)
```

**What is happening in the above output**:
- yolo detects my face
- track 1 is created
- track 1 is confirmed
- then i'm covering my face with a towel
- yolo reports that there are no detections (No detections)
- then i'm removing the towel from the screen
- right away we can see that the detection couldn't be assigned to Track 1 for some reason ([Track 1|Not Matched!])
  - this is problem one
- at the same moment, code is creating new Track 2 due to (Unmatched detection found!)
- then we can see that [Track 2|Matched!] is matched, instead 7of Track 1
- [Track 1|Not Matched!] continue failing to have a match

**Problem review**:
My guess is that Track 1 features/embedding coming from ReID model, are diluted/polluted when i'm covering my face with a towel and due to that, they are going much further away by euclidean distance from the frames when i'm removing towel from my face (the part where my face is visible for 85% to 100%)
That way, Track 2 have much cleaner picture of my face in terms of features.

**Possible Solutions**:
- possibly there should be some allowed failed assignment threshold, if detection is very close to some of the existing tracking objects (closer than others) We just skip those detections to avoid producing duplicate track object. This won't save if objects overlap for too long though... 
- possibly we should add additional layer to see how close/similar are some of the tracks and them merge them if:
  - one of the tracks is not matched and another is matched
  - retaining track_id of the track which was created earlier
- possibly we should clean track features, by somehow removing those diluted/polluted features to make matching possible again

Please let me know if i'm wrong somewhere in my thinking.

**Comment by denissabramovs** [comment]
I'm about to dive into cascading match, to find why exactly track 1 is not considering a match for my face, after towel is appearing on the screen.

**Comment by denissabramovs** [comment]
Can one detection be assigned to multiple tracks? If not, then could it be, that newly created track 2 is overtaking further detections over track 1?

**Comment by denissabramovs** [comment]
Track 2 is created when i'm detected as a person with towel over my face.
After that moment, Track 1 is failing to match anymore.

**Comment by xifen523** [comment]
I am very interested in what you have to say
I skimmed through the questions you mentioned above
I have some guesses as follows：
1. Enhancing the performance of the reid module may solve this problem
2. Switch to a different distance metric
3. Change to another matching algorithm

**Comment by denissabramovs** [comment]
I'm currently trying to understand, why track 2 is overtaking track 1 in my case and track 1 continue failing after track 2 have overtaken initiative.

**Comment by xifen523** [comment]
You can record a video and debug the entire code run

**Comment by denissabramovs** [comment]
Oh ok, so it is fitting features until track is confirmed. Then it drops collecting features for confirmed track and use that fitted graph to track distance for new, incoming frames.

So `NN_BUDGET` parameter is only working for maximum allowed frames to be fitted into the graph.
Maybe it worth adding `NN_MINIMAL_BUDGET` to enforce better model training, to provide better distance measurements of new frames?

**Comment by denissabramovs** [comment]
Shouldn't it be filling it from left to right, it's n dimensional matrix?
`cost_matrix[i] = self._metric(self.samples[target], features)`

**Comment by denissabramovs** [comment]
Oh wow, wait... It is fitting into the same space? All track features are being fit into the same space?
Then no wonder that it can't overtake after Track 2 is created...

So after target have disappeared even for a single frame, it is somewhat forwarding further detections to a new Track, which is feeding space with new features and because of that, it is returning more confidence over Track 1 features in the space.

Maybe it worth keeping separate graph/space for each Track? Then at least it would be possible to measure their similarity and merge at some point into single Track?

Let me know if i'm wrong here.

**Comment by denissabramovs** [comment]
I guess that will impact performance for too much, when comparing new detections with existing Tracks...
Maybe do both, first detect closest tracks refs in the overall graph and then work with closest tracks, dropping the farthest ones?

**Comment by denissabramovs** [comment]
@mikel-brostrom it seems it is your code, can you please comment on your code from above? Please.

**Comment by denissabramovs** [comment]
In advance, thank you very much for your work. I'm trying to understand, to possibly contribute to this project somehow.

**Comment by jckhng** [comment]
@denissabramovs 
This could help your re-id issues with the current iteration of the code. 
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/374#issuecomment-1107644303

**Comment by mikel-brostrom** [comment]
Hi @denissabramovs , @jckhng!

I introduced a huge bug in one of my latest updates.

> It is fitting into the same space? All track features are being fit into the same space? Then no wonder that it can't overtake initiative after Track 2 is created...

After the latest updated this got fixed. Now all features are inputed into the cost matrix in the right way. Check:
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/374

**Comment by denissabramovs** [comment]
Thank you, will try it soon.
