### ISSUE TITLE
ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by QiTianDaShengMaoHuiFei** [mikel-brostrom/Yolov5_DeepSort_OSNet#373]
Hello, I reported this error while running：ModuleNotFoundError: No module named 'torchreid'

**Comment by LovMone5** [comment]
check https://github.com/KaiyangZhou/deep-person-reid

**Comment by QiTianDaShengMaoHuiFei** [comment]
> Thank you. I've taken care of that problem， But a new problem arose,
Which models do I download and where do I put them to get the code running

**Comment by QiTianDaShengMaoHuiFei** [comment]
> 

I've already downloaded osnet_ibn_x1_0_imagenet.pth and osnet_ibn_x1_0_market1501_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip_jitter.pth，But there is always a problem reading the path

**Comment by mikel-brostrom** [comment]
> Hello, I reported this error while running：ModuleNotFoundError: No module named 'torchreid'

Make sure that the repo is cloned correctly by: 

`git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet.git`

and that all the requirements are installed in your environment

**Comment by unbeliveyu** [comment]
> 

how did you solve this question
