### ISSUE TITLE
Yolo confidences are used insted of track's confidences

### ISSUE THREAD

**Issue by cteant** [mikel-brostrom/Yolov5_DeepSort_OSNet#375]
Hi, I found that in line 191 of track.py, when generating the output, you simply zip output[i] and confs to obtain the confident score for each track. However, the order in output[i] does not necessary correspond to the order in confs (also their lengths may not be equal) and using "zip" may get a confident score that does not correspond to the right bbox.

**Comment by mikel-brostrom** [comment]
You are completely right here. Each conf is now passed to its corresponding track.
