### ISSUE TITLE
How to convert MOT format to kitti format?

### ISSUE THREAD

**Issue by loveZzq** [mikel-brostrom/Yolov5_DeepSort_OSNet#376]
I using kitti dataset, but the output of your project is MOT format.I try to modify the code, but i'm fail.Because, the kitti format need classname, but i don't konw after deepsort update, how to get the classname? Thanks for you answer.

**Comment by mikel-brostrom** [comment]
You have an example on how to get class-names in this line of code:

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/aea4a663f1497f824e0e8984b4687bdfefd2037f/track.py#L211
