### ISSUE TITLE
There is not boxes on video

### ISSUE THREAD

**Issue by Diva-Mio** [mikel-brostrom/Yolov5_DeepSort_OSNet#379]
Sorry about my poor English for here, my question is:

I found this problem on the first frame (and other frames) of video.
It makes viewers who watch this result video confuse( why the number is jumped?) .
I also can't find No.3 box in txt result, is it lost?

Am I do the wrong setting?
![ErrorImage](https://user-images.githubusercontent.com/86195848/165019809-a7768b16-0370-40b1-a14b-d874f5ccf9e9.jpg)
![ErrorImage2](https://user-images.githubusercontent.com/86195848/165020056-72cebc27-0ead-48f3-a42f-7317e1bad6a9.jpg)
![ErrorImage3](https://user-images.githubusercontent.com/86195848/165020459-2cf2fc05-615d-4c12-b12b-be7127184abf.jpg)

![ErrorImage4](https://user-images.githubusercontent.com/86195848/165034397-f7bd5378-7fca-432b-b148-efcfe1871701.jpg)

My OS : win11
Argument :  "--deep_sort_model osnet_x1_0_market1501 --source demo_tn1_1.avi --show-vid --classes 0  --save-vid --conf-thres 0.05 --iou-thres 0.05"
Video info : 1920X1080  20fps  .avi
![ErrorImage4](https://user-images.githubusercontent.com/86195848/165034397-f7bd5378-7fca-432b-b148-efcfe1871701.jpg)

**Comment by Diva-Mio** [comment]
Sorry about too long to answer your question.
I used "osnet_ibn_x1_0_MSMT17" this model, and i didn't retrain it.

**Comment by mikel-brostrom** [comment]
`osnet_ibn_x1_0_MSMT17` is the DeepSort model. I mean, use

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/releases/download/v3.0/crowdhuman_yolov5m.pt

for Yolov5.

**Comment by Diva-Mio** [comment]
Oh, I misunderstood you.
You're right, I used yolov5m model.
Thank you for your answer, I will try them all.
