### ISSUE TITLE
I have a question about Increase the function of personnel recognition

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/Yolov5_DeepSort_OSNet#381]
I want to add personality recognition functions similar to face recognition in the system, but the effect is not good when trying to compare the comparison of feature extraction based on the trace model of Deepsort.Difference.I think this is a model library for pedestrians, why the effect is still so bad？

**Comment by mikel-brostrom** [comment]
`I want to add personality recognition functions similar to face recognition in the system`

Sure

`but the effect is not good when trying to compare the comparison of feature extraction based on the trace model of Deepsort`

Sorry, cannot understand what you mean

**Comment by songjiahao-wq** [comment]
I understand that deepsort has the function of extracting pedestrian features .  So I want to compare the features extracted based on osnet model with the saved pedestrian feature library, and find that the recognition effect is bad。Is this wrong with my understanding?
