### ISSUE TITLE
The performance of re-id (deepsort)

### ISSUE THREAD

**Issue by brianw0924** [mikel-brostrom/Yolov5_DeepSort_OSNet#383]
Hi, I'm wondering if the re-id (deepsort) performance will be affect by yolo model.

Since I'm applying to my own scenario, I found that sometimes the re-id is too sensitive. (id changes on same object)

I'v tried tuning the deepsort parameter, but not very effective.

so I think maybe fine-tune the "yolo model" on my scenario would increase the re-id accuracy?

**Comment by mikel-brostrom** [comment]
`so I think maybe fine-tune the "yolo model" on my scenario would increase the re-id accuracy?`

If you have a custom use-case it is always advisable to train a Yolov5 on that scenario for maximum performance
