### ISSUE TITLE
How to fix `ModuleNotFoundError: No module named 'yolov5.models'`

### ISSUE THREAD

**Issue by ybonzou** [mikel-brostrom/Yolov5_DeepSort_OSNet#387]
Hi, Why do I get this error?　Please let us know how to deal with it.
" python track.py --source 0
Traceback (most recent call last):
  File "track.py", line 25, in <module
    from yolov5.models.experimental import attempt_load
ModuleNotFoundError: No module named 'yolov5.models' "

**Comment by mikel-brostrom** [comment]
This repo contains submodules. This means that you have to add a flag to `git clone` in order to fetch everything correctly. Re-clone using: `git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet.git`
