### ISSUE TITLE
Colab Notebook Problem

### ISSUE THREAD

**Issue by Dlb97** [mikel-brostrom/Yolov5_DeepSort_OSNet#388]
When trying to run the colab notebook, more specifically the cell after run inference on video the following error will pop up:
![Screen Shot 2022-05-03 at 11 47 49](https://user-images.githubusercontent.com/65009045/166433748-3d140a83-8325-4daa-96c9-7654cd7ae1dc.png)

Looking at the mentioned directory there is no such file. However when the model is replaced with :
/content/Yolov5_DeepSort_Pytorch/yolov5/models/yolov5l.pt
 it will work, the model would load and the detections are outputted . 

Although there are detections, when the video is displayed none can be seen. How could that be solved ?

Thanks !!

**Comment by mikel-brostrom** [comment]
This got fixed! Try again and let me know :)

**Comment by Dlb97** [comment]
Everything seems to be fine !! Thank you ! 
Unrelated to this specific issue, I cannot process videos that have 10 frames per second while 29fps work. Is this a strict requirement ?

**Comment by mikel-brostrom** [comment]
It shouldn't be. Do you only experience this issue in Colab?

**Comment by Dlb97** [comment]
Tried with a 10 fps video on a ubuntu ec2 instance and it works. So maybe the issue is only in collab or with the particular video I was using. I will double check .  

The results are impressive, Thank you !!
