### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by Mr0peng** [mikel-brostrom/Yolov5_DeepSort_OSNet#390]
requests.exceptions.SSLError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1rb8UN5ZzPKRc_xvtHlyDh-cSz88YX9hs (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

**Comment by mikel-brostrom** [comment]
Please check previous issues before posting. This has been brought up many times already:
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/277
