### ISSUE TITLE
How can I train my own datasets?

### ISSUE THREAD

**Issue by jkgjhfghdgfscv** [mikel-brostrom/Yolov5_DeepSort_OSNet#391]
I did not find the train.py in the deep_sort,and how can I train my own dataset

**Comment by mikel-brostrom** [comment]
The deep descriptor in this repo was trained by: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html. You can find
the submodule here: https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/tree/master/deep_sort/deep

**Comment by jkgjhfghdgfscv** [comment]
When I was building the train.py to train my own dataset from the tutorials on  https://kaiyangzhou.github.io/deep-person-reid/user_guide.html.  I found that the source code reported all kinds of errors,such as AttributeError.
I think the the source code may have some problems.I can't retrain the reid model with my own dataset
