### ISSUE TITLE
How do I train my own dataset?

### ISSUE THREAD

**Issue by jkgjhfghdgfscv** [mikel-brostrom/Yolov5_DeepSort_OSNet#392]
When I was building the train.py from the tutorials on https://kaiyangzhou.github.io/deep-person-reid/user_guide.html. There are so many errors reported from source code,such as Attribute error and so on.
I think the source code of deep_sort part may have some bugs,I can't retrain the model with my own dataset

**Comment by mikel-brostrom** [comment]
Sorry I cannot help you there. If you have question regarding that repo: https://github.com/KaiyangZhou/deep-person-reid.
You should post those there.
