### ISSUE TITLE
One tracker for all cameras

### ISSUE THREAD

**Issue by zyakubova86** [mikel-brostrom/Yolov5_DeepSort_OSNet#394]
Hi 

I am running tracker with multiple cameras. I have one global counter for all the tracker. Now tracker tracks separately every camera and assigns ID separately, as well. How can I run one tracker and it assigned IDs continuously for all cameras.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/issues/370#issuecomment-1113628795
