### ISSUE TITLE
--output no longer works as expected

### ISSUE THREAD

**Issue by lonnylundsten** [mikel-brostrom/Yolov5_DeepSort_OSNet#396]
With the previous version using the --output flag we could specifically direct the location of the saved video and text files. However, with this latest release the tracking output always seems to go in the same directory where the model is. In addition, the folder or project name seems to be tied to the model. Is this intentional? Is there some way to overwrite these new behaviors?

I realize everyone's workflow will be different but I am running jobs based on dive information and want the output to be organized based on those input files, not the particular model I am using. Again, using the --output flag in the past worked perfectly but that no longer seems to work as it once did. Any insight would be appreciated.

And, just in case you're interested, we're using yolov5 and deepsort to identify and track deep sea organisms in ROV video:
https://www.youtube.com/watch?v=gVdkpWXa9Gw

**Comment by mikel-brostrom** [comment]
Hi @lonnylundsten,

> And, just in case you're interested, we're using yolov5 and deepsort to identify and track deep sea organisms in ROV video:
> https://www.youtube.com/watch?v=gVdkpWXa9Gw

Thank you for sharing your research here! Always interesting to see what people use this tracker for.

A lot of the people didn't find that keeping track of experiments was so friendly with this repo. That is why the yolo model name and deepsort re-identificaton model name is now used to create the output folder name. However, it makes sense to be able to use a custom folder name for result storage. Will get this done in the coming weeks.

**Comment by lonnylundsten** [comment]
Excellent. Thank you!

**Comment by mikel-brostrom** [comment]
I introduced new arguments:

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/b855bd628edf86cc5ff7cee2c02f276012f0c494/track.py#L287-L288

Let me know if something isn't clear enough

**Comment by lonnylundsten** [comment]
Thank you!
