### ISSUE TITLE
Some test examples

### ISSUE THREAD

**Issue by Hinode** [mikel-brostrom/Yolov5_DeepSort_OSNet#403]
Hi Mike or somebody else, can you provide an test example video and instruction to run the tracker? Thanks.

**Comment by mikel-brostrom** [comment]
Everything is automatized. Model download, loading, source reading. You don't need to do anything more than setting up your pip environment and then run:

`python3 track.py --source <your-source>`

Where the source can be any of the following: https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet#tracking-sources
