### ISSUE TITLE
Adding Yolov5-Pip library support

### ISSUE THREAD

**Issue by kadirnar** [mikel-brostrom/Yolov5_DeepSort_OSNet#413]
Hi Mikel,

Want to use the pip version instead of downloading the Yolov5 repo? I can open a PR for it if you want.[Yolov5-Pip](https://github.com/fcakyon/yolov5-pip)

**Comment by mikel-brostrom** [comment]
> Want to use the pip version instead of downloading the Yolov5 repo?

I prefer having all the external code either as pip packages or submodules. As there is not pip package of torchreid I prefer keeping both as submodules.

**Comment by kadirnar** [comment]
I think it would make it simpler to load the Yolov5 model as a library. Thank you
