### ISSUE TITLE
track.py: error: unrecognized arguments: --deep_sort_model osnet_x0_25_msmt17 --yolo_model yolov5n.pt

### ISSUE THREAD

**Issue by YaelHamrani** [mikel-brostrom/Yolov5_DeepSort_OSNet#417]
Hi ,

I am trying to run the deep sort model osnet_x0_25_msmt17 but I am encountering the bug... it seems there has been some update in the code lately since this command worked for me but not anymore:
"
!python track.py --source /content/videoplayback.mp4 --deep_sort_model  osnet_x0_25_msmt17 --classes 0 --show-vid --save-txt --save-vid --save-crop --max-det 5 --dnn --yolo_model yolov5n.pt --img 640
"
when looking in the cloned folder it seems that  osnet_x0_25_msmt17.pt is missing from checkpoints

**Comment by mikel-brostrom** [comment]
Yes, some arguments chaged. Try:

!python track.py --source /content/videoplayback.mp4 --deep-sort-weightsl osnet_x0_25_msmt17.pt --classes 0 --show-vid --save-txt --save-vid --save-crop --max-det 5 --dnn --yolo-weights yolov5n.pt --img 640

**Comment by YaelHamrani** [comment]
@mikel-brostrom 
Thank u , now I get a different error:

Successfully loaded pretrained weights from "osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
video 1/1 (1/1366) /content/videoplayback.mp4: 384x640 3 persons, Done. YOLO:(0.011s), DeepSort:(0.031s)
: cannot connect to X server

Can u help?

**Comment by YaelHamrani** [comment]
Found the problem if anyone needs remove: --show-vid from command solves the issue
